#!/bin/bash

set -eu pipefail

mix deps.get --only prod
MIX_ENV=prod mix compile &&
npm run deploy --prefix ./assets &&
mix phx.digest &&
MIX_ENV=prod mix release --overwrite &&
rsync -r _build/prod/rel/secretwords worde:~/srv/

